name: girl_clan
description: A Flutter project for the Girl Clan app.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Core Packages
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  google_fonts: ^6.2.1
  get: ^4.6.6
  path_provider: ^2.1.3
  intl: ^0.20.2
  uuid: ^4.4.0
  rxdart: ^0.28.0

  # UI & Animation
  animated_text_kit: ^4.2.3
  shimmer: ^3.0.0
  confetti: ^0.8.0
  flutter_screenutil: ^5.8.4
  flutter_svg: ^2.2.0
  flutter_colorpicker: ^1.1.0

  # Firebase
  firebase_core: ^4.1.1
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.2
  firebase_messaging: ^16.0.3

  # Map & Location
  flutter_map: ^8.2.1
  latlong2: ^0.9.0
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  location: ^8.0.1
  google_maps_flutter: ^2.12.2
  google_places_flutter: ^2.1.0

  # Media & Sharing
  image_picker: ^1.1.2
  share_plus: ^12.0.0

  # Utilities
  modal_progress_hud_nsn: ^0.5.1
  country_picker: ^2.0.26
  flutter_inappwebview: ^6.1.5
  get_it: ^8.2.0
  locator: ^0.0.0-dev.2
  font_awesome_flutter: ^10.7.0
  device_preview: ^1.2.0
  flutter_branch_sdk:
  app_links: ^6.4.1
  flutter_local_notifications: ^17.2.1
  http: ^1.5.0
  googleapis_auth: ^2.0.0

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  change_app_package_name: ^1.5.0
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/static_assets/logo.png"
  min_sdk_android: 23
  web:
    generate: true
    image_path: "assets/static_assets/logo.png"
  windows:
    generate: true
    image_path: "assets/static_assets/logo.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/static_assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/static_assets/
    - assets/dynamic_assets/
    - assets/icons_assets/
